[package]
name = "graphene_fixtures"
version = "0.1.0"
edition = "2021"

[features]
default = ["serde"]
serde = ["dep:serde", "dep:serde_json"]

[dependencies]
slotmap = { version = "1.0", features = ["serde"] }
bitvec = "1.0"
smallvec = "1.11"
bitflags = "2.4"
serde = { version = "1.0", features = ["derive"], optional = true }
serde_json = { version = "1.0", optional = true }
graphene_core = { path = "../graphene_core"}

[dev-dependencies]
graphene_algorithms = { path = "../graphene_algorithms" }
