[package]
name = "graphene_layout"
version = "0.1.0"
edition = "2021"

[dependencies]
graphene_core = { path = "../graphene_core" }
graphene_fixtures = { path = "../graphene_fixtures" }
graphene_style = { path = "../graphene_style" }
graphene_analysis = { path = "../graphene_analysis" }


[dev-dependencies]
graphene_algorithms = { path = "../graphene_algorithms" }
